In [1]:
import torch

# Tensors

torch.Tensor classes are the tensors, obviously.  defining variables in terms of tensors that were operated on makes that variable carry a gradient function if the independent tensor has the requires_grad argument set to True.  Calling the .backward(torch.tensor(1's the same shape as the object calling this)) backpropogates the gradients onto the component tensors' .grad parameter.  These accumulate the effects of calling .backward(), i assume for the flexibility of having several outputs depend on a single tensor.  Can also stop a certain block from accumulating anything from .backward() calls that automatically happen in neural net training.  and there's spit on the table.  thank you santa monica.

In [7]:
torch.empty(2,2)

tensor([[                                       0.0000,
                                                2.0000],
        [-218072553553409255625889024007745830912.0000,
                                                0.0000]])

In [9]:
torch.rand(2,3) + torch.rand(2,3)

tensor([[0.8108, 0.6580, 0.5105],
        [1.0203, 1.4723, 1.5471]])

In [14]:
x = torch.rand(2,2)
y = torch.tensor([[0,0],
                  [1,2]], dtype=torch.float)

In [19]:
torch.add(x, y, out=x)

tensor([[0.4500, 0.2885],
        [4.2379, 8.0516]])

In [22]:
#another way to add inplace
x.add_(y)

tensor([[ 0.4500,  0.2885],
        [ 7.2379, 14.0516]])

in place operators will all end in an underscore

In [27]:
#slicing
torch.rand(3,3)[:,1:3]

tensor([[0.8513, 0.7959],
        [0.8814, 0.9536],
        [0.9854, 0.0006]])

In [28]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [29]:
x

tensor([[ 0.6029, -1.1257,  0.8131, -0.3767],
        [ 0.8756,  0.3649,  0.8592, -0.0926],
        [ 0.6054, -0.5257,  1.3566, -0.7312],
        [-0.1729, -1.1118, -1.6253, -0.3349]])

In [30]:
y

tensor([ 0.6029, -1.1257,  0.8131, -0.3767,  0.8756,  0.3649,  0.8592, -0.0926,
         0.6054, -0.5257,  1.3566, -0.7312, -0.1729, -1.1118, -1.6253, -0.3349])

In [31]:
z

tensor([[ 0.6029, -1.1257,  0.8131, -0.3767,  0.8756,  0.3649,  0.8592, -0.0926],
        [ 0.6054, -0.5257,  1.3566, -0.7312, -0.1729, -1.1118, -1.6253, -0.3349]])

Unwraps left to right, top to bottom.  view is the new reshape.

In [33]:
x[0,0].item()

0.6028594970703125

That's how you take out one element from a tensor i guess.

In [35]:
#convert to numpy
a = x.numpy()

In [36]:
a

array([[ 0.6028595 , -1.1256753 ,  0.81312853, -0.3767377 ],
       [ 0.87557375,  0.3649384 ,  0.8592395 , -0.0925917 ],
       [ 0.6053944 , -0.5256794 ,  1.3566024 , -0.73117405],
       [-0.17291704, -1.1118176 , -1.6253008 , -0.3349216 ]],
      dtype=float32)

In [37]:
#from numpy
b = torch.from_numpy(a)

In [38]:
b

tensor([[ 0.6029, -1.1257,  0.8131, -0.3767],
        [ 0.8756,  0.3649,  0.8592, -0.0926],
        [ 0.6054, -0.5257,  1.3566, -0.7312],
        [-0.1729, -1.1118, -1.6253, -0.3349]])

In [39]:
x

tensor([[ 0.6029, -1.1257,  0.8131, -0.3767],
        [ 0.8756,  0.3649,  0.8592, -0.0926],
        [ 0.6054, -0.5257,  1.3566, -0.7312],
        [-0.1729, -1.1118, -1.6253, -0.3349]])

In [40]:
y

tensor([ 0.6029, -1.1257,  0.8131, -0.3767,  0.8756,  0.3649,  0.8592, -0.0926,
         0.6054, -0.5257,  1.3566, -0.7312, -0.1729, -1.1118, -1.6253, -0.3349])

In [41]:
#this happens in place
x.requires_grad_(True)

tensor([[ 0.6029, -1.1257,  0.8131, -0.3767],
        [ 0.8756,  0.3649,  0.8592, -0.0926],
        [ 0.6054, -0.5257,  1.3566, -0.7312],
        [-0.1729, -1.1118, -1.6253, -0.3349]], requires_grad=True)

In [42]:
#appears to be elementwise multiplication
y = x*x

In [43]:
y

tensor([[0.3634, 1.2671, 0.6612, 0.1419],
        [0.7666, 0.1332, 0.7383, 0.0086],
        [0.3665, 0.2763, 1.8404, 0.5346],
        [0.0299, 1.2361, 2.6416, 0.1122]], grad_fn=<ThMulBackward>)

In [44]:
y.grad_fn

In [46]:
#when you arrive at a scalar output, you can take the gradient with the .backward() method
rmse_kinda = torch.sum((y - y.mean())**2)

In [47]:
#calculates current gradients for any element in a tensor that required gradients
#same as .backward(torch.tensor(1))
#autograd function it's called
rmse_kinda.backward()

In [48]:
x.grad

tensor([[ -0.7992,  -2.5768,  -0.1096,   0.8333],
        [  0.2513,  -0.8199,   0.1492,   0.2542],
        [ -0.7952,   0.8801,   6.2159,   0.4687],
        [  0.4599,  -2.4071, -12.6561,   0.7806]])

In [83]:
x = torch.tensor([4,5,6], dtype=torch.float)

y = 3*x

In [84]:
x.requires_grad_(True)

tensor([4., 5., 6.], requires_grad=True)

In [85]:
#this won't work. have to reinstantiate it
y.grad_fn

In [89]:
y = x.transpose(0,0)

In [90]:
y

tensor([4., 5., 6.], grad_fn=<TransposeBackward0>)

In [91]:
y.grad_fn

In [92]:
y.backward(torch.tensor([1,1,1], dtype=torch.float))

In [93]:
x.grad

tensor([1., 1., 1.])

running this repeatedly seems to keep bumping up the gradient.  has to move forward at some point i guess.  time for sleep now.  also note scalars required backward with rank 0 tensor as argument (the default).  when y was rank 1, passing in a tensor with all ones and the same dimensions produced gradients for x components.

# Creating a Neural Network using PyTorch Modules

playing off of and taking notes on the pytorch tutorial.  Here is a rip from the tutorial summarizing the objects seen here:

Recap:

torch.Tensor - A multi-dimensional array with support for autograd operations like backward(). Also holds the gradient w.r.t. the tensor.

nn.Module - Neural network module. Convenient way of encapsulating parameters, with helpers for moving them to GPU, exporting, loading, etc.

nn.Parameter - A kind of Tensor, that is automatically registered as a parameter when assigned as an attribute to a Module.

autograd.Function - Implements forward and backward definitions of an autograd operation. Every Tensor operation, creates at least a single Function node, that connects to functions that created a Tensor and encodes its history.

In [94]:
import torch.nn as nn
import torch.nn.functional as fxn

In [95]:
# extending basic neural network class from torch.nn
# knows what to do with backward, but need to define forward method and layers during init
class ANN(nn.Module):
    
    def __init__(self, input_len, hidden_nodes):
        # call nn.Module's init.  in hindsight i guess this should have to happen or else overwrite i guess
        super(ANN, self).__init__()
        self.fc = nn.Linear(input_len, hidden_nodes)
        self.out = nn.Linear(hidden_nodes, 1)
        
    def forward(self, x):
        x = fxn.relu(self.fc(x))
        x = self.out(x)
        return x

In [96]:
generic = ANN(1, 10)

In [97]:
print(generic)

ANN(
  (fc): Linear(in_features=1, out_features=10, bias=True)
  (out): Linear(in_features=10, out_features=1, bias=True)
)


In [103]:
list(generic.parameters())

[Parameter containing:
 tensor([[-0.0904],
         [ 0.0597],
         [ 0.0084],
         [-0.2758],
         [ 0.2681],
         [ 0.8497],
         [-0.9456],
         [ 0.9478],
         [-0.3208],
         [-0.7305]], requires_grad=True), Parameter containing:
 tensor([ 0.6177,  0.1303,  0.2869,  0.2174,  0.4244, -0.0081, -0.9745,  0.1199,
          0.0399,  0.0681], requires_grad=True), Parameter containing:
 tensor([[-0.1220,  0.1886,  0.0749, -0.0425, -0.0337, -0.1091, -0.2052, -0.1783,
          -0.1361,  0.1148]], requires_grad=True), Parameter containing:
 tensor([0.2503], requires_grad=True)]

This is the parameter attribute for a module class.  note that this is some weird new object that knows it's a parameter, not just a tensor.  things i took for granted: 
- all layers require gradients by default for obvious reasons.
- parameters include going from input to layer, layer biases, layers to output, output bias
- weights initialized for me, ranging from zero to one.  Hence why normalization is good.  Not to mention everything is thrown into this network GLM style.